name: Build and Package Extension

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-package:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Build the extension
      - name: Build Extension
        run: yarn run build

      # Package the extension as a .vsix file
      - name: Package Extension
        run: yarn run package:vsix

      # Verify the .vsix file exists
      - name: Verify .vsix File
        run: |
          if not exist *.vsix (
            echo "Error: No .vsix file was found!" && exit 1
          )

      # Upload the .vsix file as an artifact
      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProCommit.vsix
          path: '*.vsix'
