name: Build VSIX Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Cache Node.js modules
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: yarn install

      # Step 5: Compile the extension
      - name: Compile the extension
        run: yarn run build

      # Step 6: Package the VSIX
      - name: Package the VSIX
        run: yarn run package

      # Step 7: Upload the built VSIX file as an artifact
      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProCommit.vsix
          path: *.vsix
