name: Release and Upload Artifact

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-and-upload:
    runs-on: windows-latest

    permissions:
      contents: write
      discussions: write

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Build the extension
      - name: Build Extension
        run: yarn run build

      # Package the extension as a .vsix file
      - name: Package Extension
        run: yarn run package:vsix

      # Verify the .vsix file exists
      - name: Verify .vsix File
        run: |
          if (!(Test-Path *.vsix)) {
            Write-Error "Error: No .vsix file was found!" 
            exit 1
          }

      # Upload the .vsix file as an artifact
      - name: Upload VSIX Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProCommit.vsix
          path: '*.vsix'

      # Publish to Open VSX Registry
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}

      # Publish to Visual Studio Marketplace
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}

      # Generate release notes using Release Changelog Builder
      - name: Generate Release Notes
        id: generate_release_notes
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: .github/release-changelog-builder-config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.vsix'
          prerelease: false
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}